### PR TITLE
save current theme in local storage, manual restore current theme

### LINKED ISSUE #3: Must manually set theme upon Firefox startup
(as mentioned by @bricewge in #2)

I am guessing you are using the manual method? The manual method by default simply waits for a user click on the toolbar button to set theme. If using the weather or time method, Firefox *should* be themed upon startup. 

Is this behavior confusing? Would it be better if Zen Fox just themed the whole browser in either the Light or Dark theme upon install/launch, and then pressing the toolbar switches to dark theme? (And I'm just talking about the manual method)

### PR DESCRIPTION
**Pull request by bricewge**
Fix #3. The current theme is saved in local storage and the manual method restore the current theme at startup.

If no method is selected it default to manual.

### CODE REVIEW

**Comment by mr-islam** [comment]
Much better solution than my lazy commit in the last merge, where I just set the browser to the light theme every time the browser started / extension was installed.

I'll take my time to read this and understand it fully before merging, since I'm a noob — but thank you! From my quick reading it seem awesome :+1:

**Comment by bricewge** [comment]
Thank you for this theme, I have been waiting for a decent solarized theme on Firefox for some time.

Note that I didn't manage to find a way, with WebExtension, to import the `setTheme` function from `theme.js`. So I copied it in `settings/settings.js`, that's not the correct way to do it since it's not DRY.

**Comment by mr-islam** [comment]
Yeah it's impossible AFAIK to import a function across files, but the documentation suggests using [`runtime.onMessage`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onMessage). 

Testing this PR though, I am getting this error, when I try to apply a new theme from settings:

    TypeError: storage.themes is undefined[Learn More] settings.js:63:5

But other than that even: what's the purpose of calling that function there, lines 61-63? That sets the theme, but then it's ignoring the time or weather functions. 

-------

It's a very nice idea to save the current theme into a localstorage variable; all that `async` stuff is starting to fly over my head honestly (this gets so confusing). 

Will you take a look at this, or should I try implement it in a way that makes sense to my beginner mind?

**Comment by bricewge** [comment]
`runtime.onMessage` is definitely better than copying code in `settings.js`.
About your error I forgot to write a condition when `storage` is `undefined`.  Lines 63-64 are there because line 186 call `setTheme` with no argument to initialize the localStorage on the first run.

When writing this commit I tried to reuse your code at most; that's why I modified `setTheme` to use it with no arguments. So it's not the prettiest code ever and may have hindered your understanding of it. For the `async` stuff you need to read the doc, it took me some time for it to "click", but at the end it's only syntactic sugar on `Promise`.
If you want I can rework the PR or you can close it and train yourself be fixing it your way; as you want.

**Comment by mr-islam** [comment]
I'll take you up on that then, and implement this myself. I am reading through Eloquent Javascript, and hopefully its `async` explanations will let me understand it truly, rather than just knowing how to use it.

Thank you so much for your contributions — it's been an awesome experience :smiley: :+1:

**Pull request closed without merging**
